version: "3.9"

services:
  scraper:
    build: .
    container_name: pricetrack_scraper
    restart: unless-stopped
    volumes:
      - ./:/app
    command: python main.py
    network_mode: "host"